### ISSUE TITLE
[Anon] Bug report: Imperium.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#68] opened 2020-10-11 20:55 UTC
**File:** Imperium.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When building escort squadrons, Cobra destroyers are a + button while all other escort options are numerical entry with up/down buttons

**Comment by Mont-Fox** [comment] 2020-10-16 02:38
not sure why it does this

**Comment by Mont-Fox** [comment] 2020-10-20 03:25
this is caused by varient types under the cobra. they wont be the same ship. resolved by making a widowmaker squadron variant.

**Closed by Mont-Fox** 2020-10-20 03:25 UTC
Labels: bug
