### ISSUE TITLE
[Anon] Bug report: Imperium.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#51] opened 2020-05-02 16:07 UTC
**File:** Imperium.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** No

**Description:** Rouge trader escort list has min of 2 per option. Main rules say rouge trader may only have 1 escort total.

**Comment by Mont-Fox** [comment] 2020-10-04 03:21
Duplicate of #56

**Closed** 2020-10-08 04:14 UTC
